name: Build and deploy ASP.Net Core app to Azure Web App - __webappname__

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BACKEND_LOCATION: 'src/Pjfm.Api',

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true
          
      - name: Dotnet restore
        run: dotnet restore
        working-directory: ${{ env.BACKEND_LOCATION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ${{env.BACKEND_LOCATION}}

      - name: dotnet publish
        run: dotnet publish -c Release -o publish/out
        working-directory: ${{env.BACKEND_LOCATION}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.BACKEND_LOCATION}}/publish/out

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pjfm'
          slot-name: production
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_SETTINGS }}
          package: .